### ISSUE TITLE
not configured time zone in Systemd in LXC

### ISSUE THREAD

**Issue by le9i0nx** [debops/ansible-ntp#29]
in ubuntu 16.04 lts not configured time zone
I noticed that ntp__daemon enabled = False
I think it is right for lxc, but I think it need to configure the time zone.

``` yaml

TASK [debops.ntp : Configure tzdata area in debconf] ***************************
ok: [cups-l.74ru.mpautina.ru]
ok: [cups-r.74ru.mpautina.ru]
changed: [cups.perm.mpautina.ru]

TASK [debops.ntp : Configure tzdata zone in debconf] ***************************
ok: [cups-l.74ru.mpautina.ru]
ok: [cups-r.74ru.mpautina.ru]
ok: [cups.perm.mpautina.ru]

TASK [debops.ntp : Configure timezone in /etc/timezone] ************************
ok: [cups-l.74ru.mpautina.ru]
ok: [cups-r.74ru.mpautina.ru]
changed: [cups.perm.mpautina.ru]
--- before: /etc/timezone
+++ after: dynamically generated
@@ -1 +1 @@
-Etc/UTC
+Europe/Moscow


TASK [debops.ntp : Install required packages] **********************************
ok: [cups-l.74ru.mpautina.ru] => (item=[u'tzdata'])
ok: [cups-r.74ru.mpautina.ru] => (item=[u'tzdata'])
ok: [cups.perm.mpautina.ru] => (item=[u'tzdata'])

TASK [debops.ntp : include] ****************************************************
skipping: [cups.perm.mpautina.ru]
included: /home/le9i0nx/crypt/ansible/roles/debops.ntp/tasks/install.yml for cups-r.74ru.mpautina.ru, cups-l.74ru.mpautina.ru

TASK [debops.ntp : Ensure that alternative daemons/programs are not installed] *
ok: [cups-l.74ru.mpautina.ru] => (item=[u'ntpdate', u'ntp', u'openntpd'])
ok: [cups-r.74ru.mpautina.ru] => (item=[u'ntpdate', u'ntp', u'openntpd'])

TASK [debops.ntp : Install required packages] **********************************

TASK [debops.ntp : Manage systemd-timesyncd state] *****************************
ok: [cups-l.74ru.mpautina.ru]
ok: [cups-r.74ru.mpautina.ru]

TASK [debops.ntp : include] ****************************************************
skipping: [cups-r.74ru.mpautina.ru]
skipping: [cups-l.74ru.mpautina.ru]

TASK [debops.ntp : include] ****************************************************
skipping: [cups-r.74ru.mpautina.ru]
skipping: [cups-l.74ru.mpautina.ru]

TASK [debops.ntp : Include systemd-timesyncd configuration] ********************
included: /home/le9i0nx/crypt/ansible/roles/debops.ntp/tasks/systemd-timesyncd.yml for cups-r.74ru.mpautina.ru, cups-l.74ru.mpautina.ru

TASK [debops.ntp : Configure timezone with timedatectl] ************************
skipping: [cups-r.74ru.mpautina.ru]
skipping: [cups-l.74ru.mpautina.ru]

TASK [debops.ntp : Make sure conf override dir exists] *************************
ok: [cups-l.74ru.mpautina.ru]
ok: [cups-r.74ru.mpautina.ru]

TASK [debops.ntp : Configure systemd-timesyncd] ********************************
ok: [cups-l.74ru.mpautina.ru]
ok: [cups-r.74ru.mpautina.ru]

TASK [debops.ntp : Reconfigure tzdata] *****************************************
skipping: [cups-r.74ru.mpautina.ru]
skipping: [cups-l.74ru.mpautina.ru]
changed: [cups.perm.mpautina.ru]

TASK [debops.ntp : Make sure that Ansible local facts directory exists] ********
ok: [cups-l.74ru.mpautina.ru]
ok: [cups-r.74ru.mpautina.ru]
ok: [cups.perm.mpautina.ru]

TASK [debops.ntp : Save ntp local facts] ***************************************
ok: [cups-l.74ru.mpautina.ru]
ok: [cups-r.74ru.mpautina.ru]
ok: [cups.perm.mpautina.ru]
        to retry, use: --limit @/tmp/ntp.retry

PLAY RECAP *********************************************************************
cups-l.74ru.mpautina.ru    : ok=26   changed=0    unreachable=0    failed=0   
cups-r.74ru.mpautina.ru    : ok=26   changed=0    unreachable=0    failed=0   
cups.perm.mpautina.ru      : ok=21   changed=3    unreachable=0    failed=0   

```
