### ISSUE TITLE
Can't manage systemd-timesyncd as a standalone role

### ISSUE THREAD

**Issue by ipr-cnrs** [debops/ansible-ntp#35]
Hi :)

I can't get `systemd-timesyncd` to be managed by this role… On a Debian Stretch (KVM or physical node), all **timesyncd** tasks are just skipped.

I set some vars :

``` yml
ntp__timezone: Europe/Paris
ntp__daemon_enabled: true
ntp__daemon: 'systemd-timesyncd'
ntp__servers:
  - 'ntp.domain.tld burst iburst minpoll 4 maxpoll 4'
```

And the result of a first run of Ansible :

``` yml
ansible-playbook -i ~/depot/ansible/staging ~/depot/ansible/site.yml --limit mynode --tags ntp

PLAY [test_ansible] ************************************************************

TASK [setup] *******************************************************************
ok: [mynode]

TASK [debops.ntp : Ensure that configuration is supported] *********************
ok: [mynode] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [debops.ntp : Install required packages] **********************************
ok: [mynode] => (item=[u'tzdata'])

TASK [debops.ntp : Ensure that alternative daemons/programs are not installed] *
ok: [mynode] => (item=[u'ntpdate', u'ntp', u'openntpd'])

TASK [debops.ntp : Install required packages] **********************************

TASK [debops.ntp : Manage systemd-timesyncd state] *****************************
skipping: [mynode]

TASK [debops.ntp : Divert original /etc/ntp.conf] ******************************
skipping: [mynode]

TASK [debops.ntp : Configure NTPd] *********************************************
skipping: [mynode]

TASK [debops.ntp : Divert original /etc/openntpd/ntpd.conf] ********************
skipping: [mynode]

TASK [debops.ntp : Configure OpenNTPd] *****************************************
skipping: [mynode] => (item=etc/default/openntpd)
skipping: [mynode] => (item=etc/openntpd/ntpd.conf)

TASK [debops.ntp : Make sure conf override dir exists] *************************
skipping: [mynode]

TASK [debops.ntp : Configure systemd-timesyncd] ********************************
skipping: [mynode]

TASK [debops.ntp : Configure tzdata area in debconf] ***************************
changed: [mynode]

TASK [debops.ntp : Configure tzdata zone in debconf] ***************************
changed: [mynode]

TASK [debops.ntp : Configure timezone in /etc/timezone] ************************
ok: [mynode]

TASK [debops.ntp : Check if /etc/localtime is a symlink] ***********************
ok: [mynode]

TASK [debops.ntp : Symlink correct timezone as /etc/localtime] *****************
skipping: [mynode]

TASK [debops.ntp : Configure timezone with timedatectl] ************************
skipping: [mynode]

TASK [debops.ntp : Reconfigure tzdata] *****************************************
changed: [mynode]

TASK [debops.ntp : Make sure that Ansible local facts directory exists] ********
changed: [mynode]

TASK [debops.ntp : Save ntp local facts] ***************************************
changed: [mynode]

PLAY RECAP *********************************************************************
mynode : ok=11   changed=5    unreachable=0    failed=0
```

**Comment by ipr-cnrs** [comment]
It may come from the include condition in `ansible-ntp/tasks/install.yml` :
``` yml
- name: Include systemd-timesyncd configuration
  include: systemd-timesyncd.yml
  when: ((ansible_local|d() and ansible_local.init|d() and
          ansible_local.init == "systemd") and
          ntp__daemon == 'systemd-timesyncd')
```

I haven't got any **ansible_local.init** fact :
``` sh
ansible -u root -i ~/depot/ansible/staging -m setup mynode
…
	"ansible_local": {
	    "ntp": {
		"configured": "true",
		"daemon": "systemd-timesyncd"
	    }
	},
```
Perhaps it's set by another debops playbook/role ?
